name: flutter_code_editor
description: A customizable code field supporting syntax highlighting and code folding.
version: 0.3.3
repository: https://github.com/akvelon/flutter-code-editor

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  autotrie:
    git:
      url: https://github.com/LucazzP/autotrie.git
      ref: 1619c18
  characters: ^1.4.0
  charcode: ^1.4.0
  collection: ^1.17.2
  equatable: ^2.0.7
  flutter: { sdk: flutter }
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  http: ^1.4.0
  linked_scroll_controller: ^0.2.0
  meta: ^1.16.0
  mocktail: ^1.0.4
  scrollable_positioned_list: ^0.3.8
  tuple: ^2.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  fake_async: ^1.3.2
  flutter_test: { sdk: flutter }
  total_lints: ^3.4.0

flutter:
  uses-material-design: true
